# Generated by Django 5.1.6 on 2025-04-15 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        ('user_app', '0005_complaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('booking', 'Booking'), ('pro_upgrade', 'Pro Upgrade')], help_text='The source of the commission', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The commission amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the commission was recorded')),
                ('admin', models.ForeignKey(help_text='The admin receiving the commission', limit_choices_to={'user_type': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, help_text='The booking associated with the commission, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='user_app.booking')),
                ('travel_agent', models.ForeignKey(blank=True, help_text='The travel agent associated with the pro upgrade, if applicable', limit_choices_to={'user_type': 'travel_agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_upgrade_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
            },
        ),
    ]
