# Generated by Django 5.1.6 on 2025-03-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
