# Generated by Django 5.1.6 on 2025-04-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_customuser_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(default='Offer 15#', max_length=255),
        ),
    ]
