# Generated by Django 5.1.6 on 2025-04-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_coupon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagentprofile',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelagentprofile',
            name='pro_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
