# Generated by Django 5.1.6 on 2025-03-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent', '0003_travelpackage_travel_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='destination',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
