# Generated by Django 5.1.6 on 2025-03-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent', '0004_travelpackage_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='category',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
