# Generated by Django 5.1.6 on 2025-03-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agent', '0006_travelpackage_no_of_persons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelpackage',
            old_name='no_of_persons',
            new_name='num_persons',
        ),
    ]
