# Generated by Django 5.1.6 on 2025-03-25 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_travelagentprofile_fcm_token'),
        ('travel_agent', '0007_rename_no_of_persons_travelpackage_num_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('travel_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.travelagentprofile')),
            ],
        ),
    ]
